import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'todo-input',
  template: `
    
    <p>The title is: {{ title }}</p><input>
    <button>Save</button>
    <input [value]="generateTitle()">

    {{ generateTitle() }}
  `,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {

  private title: string = 'my title';

  constructor() { 
      this.title = 'Hello World';
      console.log('in constructor');
    this.changeTitle('I love Angular');
    console.log(this.title);
  }

  changeTitle(newTitle: string): string {
    this.title = newTitle;
    return this.title;
  }

  ngOnInit() {
    setTimeout(() => {
      this.title = 'This is not the title you are looking for';  
    }, 3000);
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

}
